# -*- coding: utf-8 -*-
"""day5_project_[Gouri].py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJbbqbLBy81V46lB8EZdcA1xvHVva4xn
"""

import pandas as pd
import matplotlib.pyplot as plt


csv_path = 'pland_data.csv'
df = pd.read_csv(csv_path)
df.head()

# num_days = df['Date'].nunique()
# print(num_days)

plt.figure(figsize=(8, 5))

for i in range(len(df)):
  plt.text(i, df['pH_level'][i] + 0.1, f"{df['pH_level'][i]:.2f}", ha='center', va='bottom')


plt.title('pH Levels Over Time')
plt.xlabel('Date')
plt.ylabel('pH Level')
plt.ylim(1,7)
plt.bar(df['Date'], df['pH_level'],color = 'green')
plt.savefig('pHlevel_plot.png')
plt.show()